apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: arkhahwsz-python
  janus-idp.io/tekton: arkhahwsz-python
  backstage.io/kubernetes-id: arkhahwsz-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: arkhahwsz-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
