apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: arkhahwsz-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: arkhahwsz-python 
  name: arkhahwsz-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: arkhahwsz-python 
