apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: arkhahwsz-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-python:afc35c9f0d7dbcd57af1b888dce8fbb1c04a7138@sha256:401ad8129e63b55dce59a033a561807246d10a138b0d051f2b443e5a45343a3e
          name: container-image
